# Generated by Django 3.2.9 on 2022-06-21 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_productimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="proudct",
            new_name="product",
        ),
    ]
