# Generated by Django 3.2.9 on 2022-06-21 07:40

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_proudct_productimage_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to="store/images",
                validators=[store.validators.validate_file_size],
            ),
        ),
    ]
